# 1. Create a 3x3x3 array with random values

In [12]:
import numpy as np

In [18]:
arr = np.random.random((3,3,3))
print(arr)

[[[0.15675522 0.10014891 0.84975915]
  [0.37177881 0.64265799 0.27131312]
  [0.77117692 0.0130091  0.87838246]]

 [[0.01658318 0.16517546 0.10785946]
  [0.76956732 0.96599707 0.03613258]
  [0.92152688 0.44125692 0.92533954]]

 [[0.51631849 0.83470596 0.92834855]
  [0.66996982 0.10907315 0.38229188]
  [0.15438877 0.82848099 0.28307427]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [33]:
arr1 = np.zeros((5,5))
arr1[1,0] = 1
arr1[2,1] = 2
arr1[3,2] = 3
arr1[4,3] = 4
print(arr1)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [54]:
arr3 = np.zeros((8,8))
arr3[1::2,::2] = 1
arr3[::2,1::2] = 1
print(arr3)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [84]:
arr5 = np.random.random((5,5))
square_aar5  = arr5 **2
add_arr5 = square_aar5.sum()
squareroot_arr5 = add_arr5 ** (1/2)
for i in arr5:
    i/squareroot_arr5
    print(i)
# note** i tried this but it no longer stays as an array so have done it from another method too

[0.01693981 0.97867645 0.71607355 0.61849477 0.4631637 ]
[0.18443441 0.60552195 0.69965444 0.78870372 0.44062733]
[0.55602289 0.03206615 0.8787114  0.91059765 0.55793395]
[0.85333288 0.7046488  0.98377181 0.65370098 0.83757058]
[0.44603623 0.55715471 0.57074115 0.88324092 0.98566654]


#  OR

In [148]:
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.6919545  0.07323106 0.52558487 0.13728744 0.36896526]
 [0.30347226 0.17628292 0.81094292 0.46473905 0.24915103]
 [0.40512279 0.48654652 0.42965357 0.93159885 0.87283911]
 [0.25185117 0.4658124  0.7380009  0.81675245 0.35979404]
 [0.6284901  0.10377373 0.28989308 0.50616582 0.32372393]]
After normalization:
[[0.72081391 0.         0.526993   0.0746258  0.34453087]
 [0.26823141 0.1200556  0.85943563 0.4561075  0.20494708]
 [0.38665446 0.48151325 0.41523285 1.         0.9315448 ]
 [0.20809275 0.45735796 0.77445804 0.86620374 0.33384639]
 [0.64687777 0.03558226 0.25241164 0.50436976 0.29182464]]


# 5. How to find common values between two arrays?

In [95]:
x = np.array(([1,2,3,4,12]))
y = np.array(([3,5,9,1,4]))
print("Array 1: ", x)
print("Array 2: ", y)
print("Common values btween x and y: ", np.intersect1d(x, y))

Array 1:  [ 1  2  3  4 12]
Array 2:  [3 5 9 1 4]
Common values btween x and y:  [1 3 4]


# 6.How to get the dates of yesterday, today and tomorrow?

In [105]:
import datetime

In [112]:
current_date = datetime.date.today()
print(f"Today's date is: {current_date}")
yesterdays = datetime.timedelta(-1)
print("Yesterday's date was: ", (current_date + yesterdays))
tomorrow = datetime.timedelta(1)
print("Tomorrow's date will be: ", (current_date + tomorrow))

Today's date is: 2020-07-25
Yesterday's date was:  2020-07-24
Tomorrow's date will be:  2020-07-26


# 7. Consider two random array A and B, check if they are equal

In [125]:
A = np.random.random((2,2))
B = np.random.random((2,2))
print(f"Array A: {A}")
print(f"Array B: {B}")
equal = np.allclose(A,B)
print(equal)

Array A: [[0.49551134 0.13439517]
 [0.25744242 0.9503256 ]]
Array B: [[0.9892038  0.17707589]
 [0.16925671 0.43397052]]
False


# 8.Create random vector of size 10 and replace the maximum value by 0

In [137]:
vector = np.random.random(10)
print(f"Original array: {vector}\n")
max_value = vector.max()
print(f"Maximum value: {max_value}\n")
vector[vector.argmax()] = 0
print(f"Maximum value changed to 0: {vector}\n")

Original array: [0.55321341 0.28346018 0.96465752 0.80177251 0.60459929 0.89509535
 0.41650206 0.9969143  0.76671555 0.51412152]

Maximum value: 0.9969142951109601

Maximum value changed to 0: [0.55321341 0.28346018 0.96465752 0.80177251 0.60459929 0.89509535
 0.41650206 0.         0.76671555 0.51412152]



# 9. How to print all the values of an array?

In [139]:
array = np.array(([1,2,3,4,5], [6,7,8,8,9]))
for i in array:
    print(i)

[1 2 3 4 5]
[6 7 8 8 9]


# 10.Subtract the mean of each row of a matrix

In [7]:
import numpy as np
print('original matrix:\n')
matrix = np.random.rand(5,10)
print(matrix)
print('\nnew matrix:\n')
new_matrix = matrix - matrix.mean()
print(new_matrix)

original matrix:

[[0.2301441  0.96750007 0.8689701  0.3186153  0.15986419 0.66764539
  0.38427022 0.88205827 0.8915461  0.54583708]
 [0.57340865 0.67720782 0.78593568 0.45305498 0.2181273  0.19536091
  0.47963438 0.10758595 0.9889327  0.44345222]
 [0.93597186 0.16531068 0.9093366  0.65285285 0.0624867  0.4367092
  0.24115331 0.14680945 0.27621327 0.70408463]
 [0.35227264 0.43548417 0.96513094 0.6449602  0.29901067 0.63134723
  0.54631975 0.43467912 0.47166082 0.54527837]
 [0.92928663 0.68522139 0.36320961 0.04724879 0.25057984 0.12004731
  0.2713205  0.60137313 0.39938834 0.22219233]]

new matrix:

[[-0.26157774  0.47577823  0.37724826 -0.17310654 -0.33185765  0.17592355
  -0.10745162  0.39033644  0.39982426  0.05411525]
 [ 0.08168681  0.18548598  0.29421384 -0.03866686 -0.27359454 -0.29636092
  -0.01208746 -0.38413588  0.49721087 -0.04826962]
 [ 0.44425002 -0.32641115  0.41761477  0.16113102 -0.42923514 -0.05501263
  -0.25056852 -0.34491238 -0.21550856  0.2123628 ]
 [-0.13944919 -0.0

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [22]:
vector_1 = np.random.rand(15)
print('Original vector:\n', vector_1)
vector_1 += 1
print("\nAdded 1 to each element:\n", vector_1)

Original vector:
 [0.21858424 0.67304376 0.43568824 0.81303039 0.77963977 0.23477947
 0.66248648 0.1119552  0.0663887  0.23874071 0.17949577 0.0943505
 0.06397098 0.45388134 0.83428827]

Added 1 to each element:
 [1.21858424 1.67304376 1.43568824 1.81303039 1.77963977 1.23477947
 1.66248648 1.1119552  1.0663887  1.23874071 1.17949577 1.0943505
 1.06397098 1.45388134 1.83428827]


# 12.How to get the diagonal of a dot product?

In [42]:
a = np.array([[15,6,6],[4,9,3],[7,8,5]])
b = np.array([[6,2,5],[8,2,2],[2,5,3]])
print("Array one:\n", a)
print("\nArray two:\n", b)
c = np.dot(a, b)
print("\nDot of a and b:\n", c)
print("\nDiagonal of c:\n", c.diagonal())

Array one:
 [[15  6  6]
 [ 4  9  3]
 [ 7  8  5]]

Array two:
 [[6 2 5]
 [8 2 2]
 [2 5 3]]

Dot of a and b:
 [[150  72 105]
 [102  41  47]
 [116  55  66]]

Diagonal of c:
 [150  41  66]


# 13.How to find the most frequent value in an array?

In [54]:
arra = np.array([1,2,2,4,6,4,5,3,2,4,6,6,6,3,5,4,3,2,4,55,6])
print(arra)
max_array = (np.bincount(arra).argmax())
print("\nMaximumly repeated value is: ", max_array)

[ 1  2  2  4  6  4  5  3  2  4  6  6  6  3  5  4  3  2  4 55  6]

Maximumly repeated value is:  4


# 14.How to get the n largest values of an array

In [59]:
x = np.arange(15)
print("Original array:")
print(x)
print (np.max(x))

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
14


# 15.How to create a record array from a regular array?

In [62]:
#regular array
regular_array = np.array([25, 24,29])
print("Regular array:\n", regular_array)
import pandas as pd
record_array = pd.DataFrame(regular_array, index=['Maths', 'Accountancy', 'economics'])
print("\nRecord array:\n", record_array)

Regular array:
 [25 24 29]

Record array:
               0
Maths        25
Accountancy  24
economics    29
